export const siteConfig = {
  name: "Veloura",
  description: "Shop wigs, bundles, closures, and accessories that help you look finished, feel confident, and check out without stress.",
  announcement: "Need help choosing? Shop online, send your order to WhatsApp, or visit our Lekki store for pickup and in-person guidance.",
  phone: "0703 289 1651",
  email: "hello@veloura.co",
  whatsapp: "https://wa.me/2347032891651",
  instagram: "https://instagram.com/veloura.co",
  address: "12A Admiralty Way, Lekki Phase 1, Lagos",
  maps: "https://www.google.com/maps/search/?api=1&query=12A+Admiralty+Way,+Lekki+Phase+1,+Lagos",
} as const;

export const storefrontRoutes = [
  "/",
  "/shop",
  "/services",
  "/services/[slug]",
  "/services/checkout/paystack",
  "/services/checkout/paystack/verify",
  "/services/booking/success",
  "/hairdressers/[id]",
  "/collections/[slug]",
  "/categories/[slug]",
  "/product/[slug]",
  "/search",
  "/wishlist",
  "/cart",
  "/checkout",
  "/order-success",
  "/login",
  "/signup",
  "/forgot-password",
  "/reset-password",
  "/account",
  "/account/orders",
  "/account/orders/[orderNumber]",
  "/account/addresses",
  "/account/profile",
  "/account/security",
  "/account/wishlist",
  "/about",
  "/contact",
  "/faq",
  "/sales",
  "/policies/shipping-policy",
  "/policies/return-policy",
  "/policies/privacy-policy",
  "/policies/terms",
] as const;

export const adminRoutes = [
  "/admin/login",
  "/admin",
  "/admin/products",
  "/admin/orders",
  "/admin/customers",
  "/admin/categories",
  "/admin/collections",
  "/admin/discounts",
  "/admin/reviews",
  "/admin/content",
  "/admin/settings",
  "/admin/analytics",
] as const;

export const architectureSummary = {
  appLayers: [
    "App Router pages under src/app for storefront and admin surfaces",
    "Reusable UI and feature components under src/components",
    "Typed commerce content and sample records under src/data",
    "Domain helpers and formatting utilities under src/lib",
    "Prisma schema and seed for production-grade persistence migration path",
  ],
  coreModels: [
    "User, Address, Product, ProductVariant, Category, Collection, Cart, CartItem",
    "Order, OrderItem, Payment, Review, Coupon, HomepageSection, WishlistItem, ShippingZone, StoreSetting",
  ],
} as const;


